// Auto-generated by C++ Social Network Backend
const graphData = {
  algorithm: {
    name: "Betweenness Centrality",
    description: "Finding bridge users who connect different parts of the network by measuring how often they appear on shortest paths between other users.",
    targetUser: -1
  },
  nodes: [
    { id: 11, label: '11', group: 'coding', title: 'Tags: coding python C++ ' },
    { id: 12, label: '12', group: 'coding', title: 'Tags: coding python javascript ' },
    { id: 100, label: '100', group: 'coding', title: 'Tags: football basketball coding painting ' },
    { id: 13, label: '13', group: 'coding', title: 'Tags: coding C++ robotics ' },
    { id: 6, label: '6', group: 'art', title: 'Tags: art music painting ' },
    { id: 16, label: '16', group: 'art', title: 'Tags: football art ' },
    { id: 3, label: '3', group: 'sports', title: 'Tags: football basketball ' },
    { id: 7, label: '7', group: 'art', title: 'Tags: art theatre ' },
    { id: 9, label: '9', group: 'art', title: 'Tags: art painting ' },
    { id: 8, label: '8', group: 'art', title: 'Tags: art music ceramics ' },
    { id: 10, label: '10', group: 'art', title: 'Tags: art music theatre ' },
    { id: 2, label: '2', group: 'sports', title: 'Tags: football gym baseball ' },
    { id: 15, label: '15', group: 'coding', title: 'Tags: coding python robotics ' },
    { id: 4, label: '4', group: 'sports', title: 'Tags: football gym ' },
    { id: 1, label: '1', group: 'sports', title: 'Tags: football gym ' },
    { id: 14, label: '14', group: 'coding', title: 'Tags: coding javascript anime ' },
    { id: 5, label: '5', group: 'sports', title: 'Tags: football baseball leadership ' }
  ],
  history: [
    { type: 'visit', id: 3, from: -1, val: 0.0563055 },
    { type: 'visit', id: 2, from: -1, val: 0.0563055 },
    { type: 'visit', id: 4, from: -1, val: 0.0563055 },
    { type: 'visit', id: 10, from: -1, val: 0.0699339 },
    { type: 'visit', id: 13, from: -1, val: 0.0569247 },
    { type: 'visit', id: 12, from: -1, val: 0.0687507 },
    { type: 'visit', id: 14, from: -1, val: 0.0569247 },
    { type: 'visit', id: 1, from: -1, val: 0.0686506 },
    { type: 'visit', id: 15, from: -1, val: 0.0569247 },
    { type: 'visit', id: 11, from: -1, val: 0.0691538 },
    { type: 'visit', id: 5, from: -1, val: 0.0805917 },
    { type: 'visit', id: 9, from: -1, val: 0.0577869 },
    { type: 'visit', id: 8, from: -1, val: 0.0577869 },
    { type: 'visit', id: 7, from: -1, val: 0.0577869 },
    { type: 'visit', id: 6, from: -1, val: 0.0992414 }
  ],
  edges: [
    { from: 11, to: 13 },
    { from: 11, to: 12 },
    { from: 11, to: 14 },
    { from: 11, to: 15 },
    { from: 12, to: 13 },
    { from: 12, to: 14 },
    { from: 12, to: 15 },
    { from: 13, to: 14 },
    { from: 13, to: 15 },
    { from: 6, to: 9 },
    { from: 6, to: 10 },
    { from: 6, to: 8 },
    { from: 6, to: 7 },
    { from: 6, to: 16 },
    { from: 3, to: 4 },
    { from: 3, to: 5 },
    { from: 7, to: 10 },
    { from: 7, to: 8 },
    { from: 7, to: 9 },
    { from: 9, to: 10 },
    { from: 8, to: 10 },
    { from: 8, to: 9 },
    { from: 10, to: 11 },
    { from: 2, to: 5 },
    { from: 2, to: 4 },
    { from: 2, to: 3 },
    { from: 4, to: 5 },
    { from: 1, to: 4 },
    { from: 1, to: 3 },
    { from: 1, to: 6 },
    { from: 1, to: 5 },
    { from: 1, to: 2 },
    { from: 14, to: 15 },
    { from: 5, to: 12 },
    { from: 5, to: 6 }
  ],
  user_details: {
    11: {
      id: 11,
      name: "User 11",
      tags: ["coding", "python", "C++"],
      friends: [10, 13, 12, 14, 15],
      friendCount: 5,
      pagerank: 0.0691538
    },
    12: {
      id: 12,
      name: "User 12",
      tags: ["coding", "python", "javascript"],
      friends: [13, 11, 14, 5, 15],
      friendCount: 5,
      pagerank: 0.0687507
    },
    100: {
      id: 100,
      name: "User 100",
      tags: ["football", "basketball", "coding", "painting"],
      friends: [],
      friendCount: 0,
      pagerank: 0.00928793
    },
    13: {
      id: 13,
      name: "User 13",
      tags: ["coding", "C++", "robotics"],
      friends: [12, 11, 14, 15],
      friendCount: 4,
      pagerank: 0.0569247
    },
    6: {
      id: 6,
      name: "User 6",
      tags: ["art", "music", "painting"],
      friends: [9, 10, 1, 5, 8, 7, 16],
      friendCount: 7,
      pagerank: 0.0992414
    },
    16: {
      id: 16,
      name: "User 16",
      tags: ["football", "art"],
      friends: [6],
      friendCount: 1,
      pagerank: 0.0213387
    },
    3: {
      id: 3,
      name: "User 3",
      tags: ["football", "basketball"],
      friends: [4, 1, 5, 2],
      friendCount: 4,
      pagerank: 0.0563055
    },
    7: {
      id: 7,
      name: "User 7",
      tags: ["art", "theatre"],
      friends: [10, 6, 8, 9],
      friendCount: 4,
      pagerank: 0.0577869
    },
    9: {
      id: 9,
      name: "User 9",
      tags: ["art", "painting"],
      friends: [6, 10, 8, 7],
      friendCount: 4,
      pagerank: 0.0577869
    },
    8: {
      id: 8,
      name: "User 8",
      tags: ["art", "music", "ceramics"],
      friends: [10, 6, 9, 7],
      friendCount: 4,
      pagerank: 0.0577869
    },
    10: {
      id: 10,
      name: "User 10",
      tags: ["art", "music", "theatre"],
      friends: [9, 6, 11, 8, 7],
      friendCount: 5,
      pagerank: 0.0699339
    },
    2: {
      id: 2,
      name: "User 2",
      tags: ["football", "gym", "baseball"],
      friends: [5, 1, 4, 3],
      friendCount: 4,
      pagerank: 0.0563055
    },
    15: {
      id: 15,
      name: "User 15",
      tags: ["coding", "python", "robotics"],
      friends: [11, 12, 13, 14],
      friendCount: 4,
      pagerank: 0.0569247
    },
    4: {
      id: 4,
      name: "User 4",
      tags: ["football", "gym"],
      friends: [3, 1, 5, 2],
      friendCount: 4,
      pagerank: 0.0563055
    },
    1: {
      id: 1,
      name: "User 1",
      tags: ["football", "gym"],
      friends: [4, 3, 6, 5, 2],
      friendCount: 5,
      pagerank: 0.0686506
    },
    14: {
      id: 14,
      name: "User 14",
      tags: ["coding", "javascript", "anime"],
      friends: [11, 12, 13, 15],
      friendCount: 4,
      pagerank: 0.0569247
    },
    5: {
      id: 5,
      name: "User 5",
      tags: ["football", "baseball", "leadership"],
      friends: [4, 3, 12, 1, 6, 2],
      friendCount: 6,
      pagerank: 0.0805917
    }
  }
};
