// Auto-generated by C++ Social Network Backend
const graphData = {
  algorithm: {
    name: "Shortest Path (BFS)",
    description: "Finding shortest path using Breadth-First Search. Explores the network level by level to find the minimum number of hops between users.",
    targetUser: 1
  },
  nodes: [
    { id: 2, label: '2', group: 'sports', title: 'Tags: baseball gym football ' },
    { id: 4, label: '4', group: 'sports', title: 'Tags: gym football ' },
    { id: 90, label: '90', group: 'art', title: 'Tags: football art ' },
    { id: 3, label: '3', group: 'sports', title: 'Tags: basketball football ' },
    { id: 10, label: '10', group: 'art', title: 'Tags: theatre music art ' },
    { id: 11, label: '11', group: 'coding', title: 'Tags: C++ python coding ' },
    { id: 100, label: '100', group: 'coding', title: 'Tags: painting coding basketball football ' },
    { id: 13, label: '13', group: 'coding', title: 'Tags: robotics C++ coding ' },
    { id: 12, label: '12', group: 'coding', title: 'Tags: javascript python coding ' },
    { id: 14, label: '14', group: 'coding', title: 'Tags: anime javascript coding ' },
    { id: 1, label: '1', group: 'sports', title: 'Tags: gym football ' },
    { id: 15, label: '15', group: 'coding', title: 'Tags: robotics python coding ' },
    { id: 5, label: '5', group: 'sports', title: 'Tags: leadership baseball football ' },
    { id: 6, label: '6', group: 'art', title: 'Tags: painting music art ' },
    { id: 9, label: '9', group: 'art', title: 'Tags: painting art ' },
    { id: 8, label: '8', group: 'art', title: 'Tags: ceramics music art ' },
    { id: 7, label: '7', group: 'art', title: 'Tags: theatre art ' },
    { id: 16, label: '16', group: 'art', title: 'Tags: art football ' }
  ],
  history: [
    { type: 'visit', id: 1, from: -1, val: 0 },
    { type: 'visit', id: 1, from: -1, val: 0 },
    { type: 'scan', id: 5, from: -1, val: 0 },
    { type: 'scan', id: 4, from: -1, val: 0 },
    { type: 'scan', id: 2, from: -1, val: 0 },
    { type: 'scan', id: 3, from: -1, val: 0 },
    { type: 'scan', id: 6, from: -1, val: 0 },
    { type: 'visit', id: 5, from: -1, val: 0 },
    { type: 'scan', id: 12, from: -1, val: 0 },
    { type: 'visit', id: 4, from: -1, val: 0 },
    { type: 'visit', id: 2, from: -1, val: 0 },
    { type: 'visit', id: 3, from: -1, val: 0 },
    { type: 'visit', id: 6, from: -1, val: 0 },
    { type: 'scan', id: 16, from: -1, val: 0 },
    { type: 'scan', id: 7, from: -1, val: 0 },
    { type: 'scan', id: 8, from: -1, val: 0 },
    { type: 'scan', id: 10, from: -1, val: 0 },
    { type: 'scan', id: 9, from: -1, val: 0 },
    { type: 'visit', id: 12, from: -1, val: 0 },
    { type: 'scan', id: 15, from: -1, val: 0 },
    { type: 'scan', id: 14, from: -1, val: 0 },
    { type: 'scan', id: 13, from: -1, val: 0 },
    { type: 'scan', id: 11, from: -1, val: 0 },
    { type: 'visit', id: 16, from: -1, val: 0 },
    { type: 'visit', id: 7, from: -1, val: 0 },
    { type: 'visit', id: 8, from: -1, val: 0 },
    { type: 'visit', id: 10, from: -1, val: 0 },
    { type: 'visit', id: 9, from: -1, val: 0 },
    { type: 'visit', id: 15, from: -1, val: 0 },
    { type: 'visit', id: 14, from: -1, val: 0 },
    { type: 'visit', id: 13, from: -1, val: 0 },
    { type: 'visit', id: 11, from: -1, val: 0 },
    { type: 'scan', id: 90, from: -1, val: 0 },
    { type: 'visit', id: 90, from: -1, val: 0 },
    { type: 'path', id: 90, from: -1, val: 0 },
    { type: 'path', id: 11, from: -1, val: 0 },
    { type: 'path', id: 12, from: -1, val: 0 },
    { type: 'path', id: 5, from: -1, val: 0 },
    { type: 'path', id: 1, from: -1, val: 0 }
  ],
  edges: [
    { from: 2, to: 4 },
    { from: 2, to: 5 },
    { from: 2, to: 3 },
    { from: 4, to: 5 },
    { from: 3, to: 5 },
    { from: 3, to: 4 },
    { from: 10, to: 11 },
    { from: 11, to: 15 },
    { from: 11, to: 14 },
    { from: 11, to: 90 },
    { from: 11, to: 12 },
    { from: 11, to: 13 },
    { from: 13, to: 15 },
    { from: 13, to: 14 },
    { from: 12, to: 15 },
    { from: 12, to: 14 },
    { from: 12, to: 13 },
    { from: 14, to: 15 },
    { from: 1, to: 5 },
    { from: 1, to: 4 },
    { from: 1, to: 2 },
    { from: 1, to: 3 },
    { from: 1, to: 6 },
    { from: 5, to: 6 },
    { from: 5, to: 12 },
    { from: 6, to: 16 },
    { from: 6, to: 7 },
    { from: 6, to: 8 },
    { from: 6, to: 10 },
    { from: 6, to: 9 },
    { from: 9, to: 10 },
    { from: 8, to: 10 },
    { from: 8, to: 9 },
    { from: 7, to: 9 },
    { from: 7, to: 8 },
    { from: 7, to: 10 }
  ],
  user_details: {
    2: {
      id: 2,
      name: "User 2",
      tags: ["baseball", "gym", "football"],
      friends: [4, 1, 5, 3],
      friendCount: 4,
      pagerank: 0.0533863
    },
    4: {
      id: 4,
      name: "User 4",
      tags: ["gym", "football"],
      friends: [5, 1, 2, 3],
      friendCount: 4,
      pagerank: 0.0533863
    },
    90: {
      id: 90,
      name: "User 90",
      tags: ["football", "art"],
      friends: [11],
      friendCount: 1,
      pagerank: 0.0208096
    },
    3: {
      id: 3,
      name: "User 3",
      tags: ["basketball", "football"],
      friends: [2, 5, 1, 4],
      friendCount: 4,
      pagerank: 0.0533863
    },
    10: {
      id: 10,
      name: "User 10",
      tags: ["theatre", "music", "art"],
      friends: [8, 9, 7, 6, 11],
      friendCount: 5,
      pagerank: 0.0673942
    },
    11: {
      id: 11,
      name: "User 11",
      tags: ["C++", "python", "coding"],
      friends: [15, 14, 90, 12, 13, 10],
      friendCount: 6,
      pagerank: 0.0851527
    },
    100: {
      id: 100,
      name: "User 100",
      tags: ["painting", "coding", "basketball", "football"],
      friends: [],
      friendCount: 0,
      pagerank: 0.00874636
    },
    13: {
      id: 13,
      name: "User 13",
      tags: ["robotics", "C++", "coding"],
      friends: [15, 14, 12, 11],
      friendCount: 4,
      pagerank: 0.0561408
    },
    12: {
      id: 12,
      name: "User 12",
      tags: ["javascript", "python", "coding"],
      friends: [15, 5, 14, 13, 11],
      friendCount: 5,
      pagerank: 0.0674784
    },
    14: {
      id: 14,
      name: "User 14",
      tags: ["anime", "javascript", "coding"],
      friends: [15, 13, 12, 11],
      friendCount: 4,
      pagerank: 0.0561408
    },
    1: {
      id: 1,
      name: "User 1",
      tags: ["gym", "football"],
      friends: [5, 4, 2, 3, 6],
      friendCount: 5,
      pagerank: 0.0651283
    },
    15: {
      id: 15,
      name: "User 15",
      tags: ["robotics", "python", "coding"],
      friends: [14, 13, 12, 11],
      friendCount: 4,
      pagerank: 0.0561408
    },
    5: {
      id: 5,
      name: "User 5",
      tags: ["leadership", "baseball", "football"],
      friends: [1, 4, 2, 3, 6, 12],
      friendCount: 6,
      pagerank: 0.0767925
    },
    6: {
      id: 6,
      name: "User 6",
      tags: ["painting", "music", "art"],
      friends: [16, 7, 8, 5, 1, 10, 9],
      friendCount: 7,
      pagerank: 0.0944527
    },
    9: {
      id: 9,
      name: "User 9",
      tags: ["painting", "art"],
      friends: [8, 10, 7, 6],
      friendCount: 4,
      pagerank: 0.0550828
    },
    8: {
      id: 8,
      name: "User 8",
      tags: ["ceramics", "music", "art"],
      friends: [10, 9, 7, 6],
      friendCount: 4,
      pagerank: 0.0550828
    },
    7: {
      id: 7,
      name: "User 7",
      tags: ["theatre", "art"],
      friends: [9, 8, 10, 6],
      friendCount: 4,
      pagerank: 0.0550828
    },
    16: {
      id: 16,
      name: "User 16",
      tags: ["art", "football"],
      friends: [6],
      friendCount: 1,
      pagerank: 0.0202156
    }
  }
};
